build_command:
- docker
- build
- -t
- '{tag}'
- -f
- '{dockerfile}'
- .
description: This is a vanilla flavour
dockerfile: Dockerfile
selectors: []
docker_params: ["--device=/dev/dri", "-v /dev/dri/by-path:/dev/dri/by-path"]
