build_command:
- docker
- build
- -t
- '{tag}'
- -f
- '{dockerfile}'
- .
description: This is a vanilla flavour
dockerfile: Dockerfile
selectors:
  - kind: rocm
    apiVersion: "6.1"
    apiThing: "v1"
