app_images:
- appImageId: 98da5ca5645e4959afff078f381a5e85
  flavourName: cuda
  image:
    buildAt: '2024-10-29T18:44:17.136359'
    imageString: alexanderschroeter/tensorflow-test:0.0.1-cuda
  inspection:
    requirements:
    - description: An instance of ArkitektNext Lok to authenticate the user
      key: lok
      optional: false
      service: live.arkitekt.lok
    - description: An instance of ArkitektNext fluss to retrieve graphs from
      key: fluss
      optional: false
      service: live.arkitekt.fluss
    - description: An instance of ArkitektNext Kabinet to retrieve nodes from
      key: kabinet
      optional: false
      service: live.arkitekt.kabinet
    - description: An instance of ArkitektNext Lok to authenticate the user
      key: livekit
      optional: false
      service: io.livekit.livekit
    - description: An instance of ArkitektNext Mikro to make requests to the user's
        data
      key: mikro
      optional: true
      service: live.arkitekt.mikro
    - description: An instance of ArkitektNext Datalayer to make requests to the user's
        data
      key: datalayer
      optional: true
      service: live.arkitekt.s3
    - description: An instance of ArkitektNext Rekuest to assign to nodes
      key: rekuest
      optional: false
      service: live.arkitekt.rekuest
    - description: An instance of ArkitektNext Lok to authenticate the user
      key: unlok
      optional: false
      service: live.arkitekt.lok
    size: 7704544242
    templates:
    - definition:
        args: []
        collections: []
        description: Returns a string with the tensorflow version
        interfaces: []
        isDev: false
        isTestFor: []
        kind: FUNCTION
        name: Version
        portGroups: []
        returns:
        - description: A string with the version of tensorflow
          key: return0
          kind: STRING
          nullable: false
          scope: GLOBAL
        stateful: false
      dependencies: []
      dynamic: false
      interface: version
    - definition:
        args: []
        collections: []
        description: Returns a string of the available physical devices.
        interfaces: []
        isDev: false
        isTestFor: []
        kind: FUNCTION
        name: List Gpus
        portGroups: []
        returns:
        - description: list of physical devices
          key: return0
          kind: STRING
          nullable: false
          scope: GLOBAL
        stateful: false
      dependencies: []
      dynamic: false
      interface: list_gpus
  manifest:
    author: Alexander Wilhelmi
    entrypoint: app
    identifier: tensorflow-test
    scopes:
    - read
    version: 0.0.1
  selectors:
  - kind: cuda
- appImageId: c036620a1da54d17af465d3c3ec28b9b
  flavourName: rocm
  image:
    buildAt: '2024-10-29T18:45:31.774049'
    imageString: alexanderschroeter/tensorflow-test:0.0.1-rocm
  inspection:
    requirements:
    - description: An instance of ArkitektNext Lok to authenticate the user
      key: lok
      optional: false
      service: live.arkitekt.lok
    - description: An instance of ArkitektNext fluss to retrieve graphs from
      key: fluss
      optional: false
      service: live.arkitekt.fluss
    - description: An instance of ArkitektNext Kabinet to retrieve nodes from
      key: kabinet
      optional: false
      service: live.arkitekt.kabinet
    - description: An instance of ArkitektNext Lok to authenticate the user
      key: livekit
      optional: false
      service: io.livekit.livekit
    - description: An instance of ArkitektNext Mikro to make requests to the user's
        data
      key: mikro
      optional: true
      service: live.arkitekt.mikro
    - description: An instance of ArkitektNext Datalayer to make requests to the user's
        data
      key: datalayer
      optional: true
      service: live.arkitekt.s3
    - description: An instance of ArkitektNext Rekuest to assign to nodes
      key: rekuest
      optional: false
      service: live.arkitekt.rekuest
    - description: An instance of ArkitektNext Lok to authenticate the user
      key: unlok
      optional: false
      service: live.arkitekt.lok
    size: 37077062751
    templates:
    - definition:
        args: []
        collections: []
        description: Returns a string with the tensorflow version
        interfaces: []
        isDev: false
        isTestFor: []
        kind: FUNCTION
        name: Version
        portGroups: []
        returns:
        - description: A string with the version of tensorflow
          key: return0
          kind: STRING
          nullable: false
          scope: GLOBAL
        stateful: false
      dependencies: []
      dynamic: false
      interface: version
    - definition:
        args: []
        collections: []
        description: Returns a string of the available physical devices.
        interfaces: []
        isDev: false
        isTestFor: []
        kind: FUNCTION
        name: List Gpus
        portGroups: []
        returns:
        - description: list of physical devices
          key: return0
          kind: STRING
          nullable: false
          scope: GLOBAL
        stateful: false
      dependencies: []
      dynamic: false
      interface: list_gpus
  manifest:
    author: Alexander Wilhelmi
    entrypoint: app
    identifier: tensorflow-test
    scopes:
    - read
    version: 0.0.1
  selectors:
  - kind: rocm
latest_app_image: c036620a1da54d17af465d3c3ec28b9b
