build_command:
- docker
- build
- -t
- '{tag}'
- -f
- '{dockerfile}'
- .
description: This is a vanilla flavour
dockerfile: Dockerfile
selectors: []
docker_params: ["--device=/dev/kfd", "--device=/dev/dri", "--group-add video"]
